apiVersion: 1

datasources:
  - name: Sofia-Telemetry-API
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://backend:8001/api/admin/geo-telemetry
    editable: true
    jsonData:
      datasource_mode: "advanced"
